wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.16.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718270934.0
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.12.1
      5: 0.16.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
