_wandb:
    value:
        cli_version: 0.21.0
        e:
            dsbxevgsu1fpm2c289wj90ixv3sjpta9:
                codePath: Pipeline/Models/DL_XGBoost/forecasting_pipeline_IHEPC_dataset.ipynb
                codePathLocal: forecasting_pipeline_IHEPC_dataset.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1005867986944"
                        used: "210846081024"
                email: steliosbombai@gmail.com
                executable: /home/stelio/miniconda3/envs/tensorflow_gpu/bin/python
                git:
                    commit: 496988534779626807dc77ea385fdf7a92558bed
                    remote: https://github.com/it21346/tSDG-DiffusionTS-DataAugmentation.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-b405f467-289f-5919-b037-fe52b806b144
                host: stelio-LOQ-15ARP9
                memory:
                    total: "24864428032"
                os: Linux-6.11.0-26-generic-x86_64-with-glibc2.39
                program: /home/stelio/Desktop/PhD/Paper/tSDG-DiffusionTS-DataAugmentation/Pipeline/Models/DL_XGBoost/forecasting_pipeline_IHEPC_dataset.ipynb
                python: CPython 3.12.2
                root: /home/stelio/Desktop/PhD/Paper/tSDG-DiffusionTS-DataAugmentation/Pipeline/Models/DL_XGBoost
                startedAt: "2025-10-08T09:56:48.098116Z"
                writerId: dsbxevgsu1fpm2c289wj90ixv3sjpta9
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "2": epoch/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.2
        t:
            "1":
                - 2
                - 3
                - 5
                - 6
                - 53
            "2":
                - 2
                - 3
                - 5
                - 6
                - 53
            "3":
                - 2
                - 7
                - 14
                - 17
                - 38
            "4": 3.12.2
            "5": 0.21.0
            "8":
                - 1
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 32
data_augmentation:
    value: false
fake_data_length:
    value: 0
model_name:
    value: BiLSTM
pinball_loss_usage:
    value: false
scaler_name:
    value: standard
seed:
    value: 4242
testing_stage:
    value: false
