_wandb:
    value:
        cli_version: 0.18.5
        m:
            - "1": epoch/mape
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/mae
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_mae
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_mape
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.2
        t:
            "1":
                - 2
                - 3
                - 5
                - 6
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 7
                - 17
                - 23
                - 38
                - 55
            "4": 3.12.2
            "5": 0.18.5
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 64
data_augmentation:
    value: true
fake_data_length:
    value: 0.5
model_name:
    value: LSTM
pinball_loss_usage:
    value: false
scaler_name:
    value: standard
seed:
    value: 2021
testing_stage:
    value: true
