runs:
  - task: 'estimation'
    categorical: 'on'
    interval: '15min'
    model_type: 'XGBoost'
    prediction_mode: 0
    multisteps: 4
    batch_size: 8
    epochs: 70
  # - task: 'timeseries'
  #   categorical: 'on'
  #   interval: '15min'
  #   model_type: 'BiLSTM'
  #   prediction_mode: 0
  #   multisteps: 4
  #   batch_size: 8
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'off'
  #   interval: '15min'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 4
  #   batch_size: 8
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'on'
  #   interval: '15min'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 4
  #   batch_size: 8
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'off'
  #   interval: '4h'
  #   model_type: 'BiLSTM'
  #   prediction_mode: 0
  #   multisteps: 4
  #   batch_size: 8
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'on'
  #   interval: '4h'
  #   model_type: 'BiLSTM'
  #   prediction_mode: 0
  #   multisteps: 4
  #   batch_size: 8
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'off'
  #   interval: '4h'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 4
  #   batch_size: 8
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'on'
  #   interval: '4h'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 4
  #   batch_size: 8
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'on'
  #   interval: '1h'
  #   model_type: 'BiLSTM'
  #   prediction_mode: 1
  #   multisteps: 4
  #   batch_size: 8
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'on'
  #   interval: '1d'
  #   model_type: 'BiLSTM'
  #   prediction_mode: 0
  #   multisteps: 4
  #   batch_size: 2
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'off'
  #   interval: '1d'
  #   model_type: 'BiLSTM'
  #   prediction_mode: 0
  #   multisteps: 4
  #   batch_size: 2
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'on'
  #   interval: '1d'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 4
  #   batch_size: 2
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'off'
  #   interval: '1d'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 4
  #   batch_size: 2
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'on'
  #   interval: '4h'
  #   model_type: 'BiLSTM'
  #   prediction_mode: 1
  #   multisteps: 6
  #   batch_size: 2
  #   epochs: 70
  # - task: 'timeseries'
  #   categorical: 'on'
  #   interval: '1d'
  #   model_type: 'BiLSTM'
  #   prediction_mode: 1
  #   multisteps: 7
  #   batch_size: 2
  #   epochs: 70
  # - task: 'estimation'
  #   categorical: 'on'
  #   interval: '15min'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 7
  #   batch_size: 2
  #   epochs: 70
  # - task: 'estimation'
  #   categorical: 'off'
  #   interval: '15min'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 7
  #   batch_size: 2
  #   epochs: 70
  # - task: 'estimation'
  #   categorical: 'off'
  #   interval: '4h'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 7
  #   batch_size: 2
  #   epochs: 70
  # - task: 'estimation'
  #   categorical: 'on'
  #   interval: '4h'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 7
  #   batch_size: 2
  #   epochs: 70
  # - task: 'estimation'
  #   categorical: 'off'
  #   interval: '1d'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 7
  #   batch_size: 2
  #   epochs: 70
  # - task: 'estimation'
  #   categorical: 'on'
  #   interval: '1d'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 7
  #   batch_size: 2
  #   epochs: 70
  # - task: 'estimation'
  #   categorical: 'on'
  #   interval: '1w'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 7
  #   batch_size: 2
  #   epochs: 70
  # - task: 'estimation'
  #   categorical: 'off'
  #   interval: '1w'
  #   model_type: 'XGBoost'
  #   prediction_mode: 0
  #   multisteps: 7
  #   batch_size: 2
  #   epochs: 70
